title: Shane K. Panter
description: Shane's personal website
url: "https://shanepanter.com/"

# Build settings
future: true
show_drafts: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll_version_plugin

exclude:
  - preview-theme.sh
  - package-theme.sh
  - README.md
  - LICENSE

# Add in new classes here and they will show up on the main index
collections:
  web:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "course"
